### PR TITLE
Move auth from sdk to runtime

### PR DESCRIPTION
**Pull request by harryi3t**
Checklist
- [x] move all sign functions + dependencies
- [x] expose independent `authorize` functionality to the outer world
- [x] support VariableList as auth type
- [x] copy auth tests (relevant unit and integration) from SDK. [refer to removed tests](https://github.com/postmanlabs/postman-collection/pull/446)
- [x] add a markdown file listing the auth variable structure (which will be linked from SDK docs)

### CODE REVIEW

**Comment by shamasis** [comment]
Also remember to add system test

```
            // Hawk library v3.1.2+ uses ES6 and is not compatible with the browser.
            it('hawk version', function () {
                expect(json.dependencies.hawk).to.be('3.1.3');
            });
```

**Comment by shamasis** [comment]
Also file-type version latest is ES6.

They need to be added to greenKeeper Ignore

**Comment by harryi3t** [comment]
@shamasis Doc for the updated auth architecture
https://github.com/postmanlabs/postman-runtime/blob/fa6bd7af9e549e5dc0ef4c0a65cde0142b52c2c7/docs/architecture.md#authorizer

**Comment by harryi3t** [comment]
@shamasis Doc for the updated auth architecture

https://github.com/postmanlabs/postman-runtime/blob/1be3a4fe795381617d2bd701516ebc68f7492370/docs/architecture.md#authorizer

**Comment by harryi3t** [comment]
@shamasis 

> Also file-type version latest is ES6.
> 
> They need to be added to greenKeeper Ignore

In runtime we don't have this package, only the `hawk` package has been moved here.
I have added `hawk` to `greenKeeper Ignore` section

**Pull request merged**
