### PR TITLE
Renamed requester util.js to core.js

### PR DESCRIPTION
**Pull request by czardoz**
Perhaps it's time?

### CODE REVIEW

**Comment by kunagpal** [comment]
@debjeet-sarkar 😄

**Comment by debjeet-sarkar** [comment]
@kunagpal, yes, circles.

**Comment by shamasis** [comment]
The most hilarious commit of all times.

**Comment by czardoz** [comment]
@shamasis Now we need a _real_ `utils.js` with all the random functions thrown it :stuck_out_tongue:

**Pull request merged**
