### PR TITLE
[WIP] Fix eslint config to lint all files in lib and test

### PR DESCRIPTION
**Pull request by kamalaknn**
There are still `305` errors. Good news is a lot of it is unused vars and max line errors.

### CODE REVIEW

**Comment by kunagpal** [comment]
@kamalaknn A change this big should go in smaller parts 😞

**Comment by kamalaknn** [comment]
@kunagpal yeah, but however it is, it has to go before 7.0

**Comment by kunagpal** [comment]
@kamalaknn Separate P.Rs please?

**Comment by kamalaknn** [comment]
@kunagpal how do you want them?

Fixes by rule, fixes by files?

**Comment by kunagpal** [comment]
The latter. For instance:
1. Unit + system tests
2. Integration tests
3. Legacy integration tests
4. npm scripts + index.js
5. One for each lib subfolder.

**Comment by kamalaknn** [comment]
Sending smaller PRs

**Pull request closed without merging**
