### PR TITLE
Allowed whitelisted keywords in request body keys

### PR DESCRIPTION
**Pull request by kunagpal**
Discovered by @ahmad-511 in https://github.com/postmanlabs/postman-app-support/issues/4397.

### CODE REVIEW

**Comment by kamalaknn** [comment]
@kunagpal can you extract the commits for nsp exclusions into a separate PR? We'll get it merged first.

It'll keep the changes minimal in this PR.

**Comment by kamalaknn** [comment]
@kunagpal Looks good to me. Can you run this by @shamasis once, if he has a better approach?

**Comment by shamasis** [comment]
I see repeated code which can be better moved to a helper function.

**Comment by shamasis** [comment]
Also why can’t we do simple hasOwnProperty in those?

**Comment by kunagpal** [comment]
@shamasis 
```js
var a = {};
a.hasOwnProperty('constructor'); // false

var b = { constructor: '234' };
b.hasOwnProperty('constructor'); // true
```

**Comment by kunagpal** [comment]
@shamasis Addressed comments.

**Comment by kunagpal** [comment]
@kamalaknn I'll revert those commits once hawk and postman-request have been bumped.

**Pull request merged**
