### PR TITLE
add an option 'requestMethod' to determine if run only a specific met…

### PR DESCRIPTION
**Pull request by questionlin**
Hi guys, I add an option to the options, which determine if newman runs 'get' or 'post' only.
This is the first time I pull a request. If I made any mistake, please tell me.

### CODE REVIEW

**Comment by shamasis** [comment]
Hello. The PR is failing tests and does not add tests for the new options - both unit and integration tests missing. 

But more importantly, what's the use case of this feature? Can this not be achieved using setNextRequest or by filtering the collection before it is sent to Newman?

We usually avoid adding features to runtime that does not have long term impact on Postman apps, our monitoring product and Newman.

**Comment by shamasis** [comment]
Pending close if this can be achieved stern ally outside runtime.

**Comment by questionlin** [comment]
Sometimes I wanna only test GET requests. It's OK to filter the collection. If you think It's not a necessary feature, just ignore it.

**Comment by czardoz** [comment]
@questionlin A better way to do that would be, using the SDK: https://github.com/postmanlabs/postman-collection.

For example: 

```javascript
var sdk = require('postman-collection');
var collectionJson = {
    // Your collection V2 JSON
}

var completeCollection = new sdk.Collection(collectionJson);
var getCollection = new sdk.Collection(); 

completeCollection.forEachItem(function (item) {
    if (item.request.method === 'GET') {
        // If method is 'GET', add it to the getCollection
        getCollection.items.add(item);
    }
});

// You can now run the "getCollection" in runtime!
```

**Comment by czardoz** [comment]
@questionlin I've closed this PR for now, feel free to reopen if you have any further questions :smile:

**Comment by questionlin** [comment]
@czardoz  cool! Thank you!

**Pull request closed without merging**
